### PR TITLE
Fixed typo

### PR DESCRIPTION
**Pull request by sunesimonsen**

### CODE REVIEW

**Comment by sunesimonsen** [comment]
@stramel I signed the CLA.

**Comment by stramel** [comment]
@sunesimonsen unfortunately my approval doesn't count 😅

**Comment by sunesimonsen** [comment]
Hehe - no sweat, I just wanted to get something though to see if it was difficult. If it is easy, I might consider contributing something real.

**Comment by stramel** [comment]
Just kinda depends, sometimes they get swamped with other things and sometimes you blink and it's merged.

**Comment by justinfagnani** [comment]
In this case, something in-between ;)

Thanks @sunesimonsen!

**Pull request merged**
