### PR TITLE
Remove attributes with nullish values

### LINKED ISSUE #86: Allow conditional creation of attributes
lit currently doesn't allow you to conditionally create an attribute.

For example, if you would like to toggle 'checked' state on an input.

<input type="checkbox" checked>

There is no way to conditionally toggle the 'checked' attribute.

This may be related to https://github.com/PolymerLabs/lit-html/issues/56 but that seems to expect undefined to not serialize, but does not mention removing attributes.

### PR DESCRIPTION
**Pull request by jridgewell**
Fixes #86.

### CODE REVIEW

**Comment by justinfagnani** [comment]
@jridgewell we still have a little discussion to do on the exact semantics we want wrt `null` and `undefined`, like in https://github.com/PolymerLabs/lit-html/issues/56#issuecomment-327623363

> The question for me, especially in lit-html core as opposed to lit-extended, is how much should an attribute binding behave like setAttribute(), and how does a full-binding relate to an interpolation. Would it be surprising that <div foo=${undefined}> behaves different than setAttribute('foo', undefined), or different than <div foo=" ${undefined} "> (note the spaces).

We'll talk about this next week, maybe in #56

**Comment by jridgewell** [comment]
It seems Glimmer follows roughly this. If there attribute has no interpolation, it checks for nully values and removes the attributes if so. If there is interpolation, it filters nully values from the string. So:

```js
html`<div attr=${null}></div>`; // => <div>
html`<div attr="${null}"></div>`; // => <div>
html`<div attr=" ${null}"></div>`; // => <div attr=" null">, glimmer would do " "
html`<div attr="${null} "></div>`; // => <div attr="null ">, glimmer would do " "
html`<div attr=" ${null} "></div>`; // => <div attr=" null ">, glimmer would do "  "

html`<div attr=${false}></div>`; // => <div attr="false">
html`<div attr="${false}"></div>`; // => <div attr="false">
html`<div attr=" ${false}"></div>`; // => <div attr=" false">, glimmer would do " false"
html`<div attr="${false} "></div>`; // => <div attr="false ">, glimmer would do "false "
html`<div attr=" ${false} "></div>`; // => <div attr=" false ">, glimmer would do " false "
```

That all seems pretty good to me.

**Comment by derappelt** [comment]
@jridgewell 
This maybe a solution, but  I think it can be confusing. There may be cases where you want to set an attribute to null. And in this cases attr=${null} or attr="${null}" would not do what you would expect.
What I would like more is something like:
`<div ${(condition) ? "attr" : ""}> or <div ${(condition) ? "attr" : null}>` if something like this even possible

**Comment by jridgewell** [comment]
Attributes are strings, though. If you want `attr="null"`, pass (the string) `"null"` as the value.

> `<div ${(condition) ? "attr" : ""}>`

I have my eye on that (specifically, attribute bindings that aren't the value), just haven't gotten around to it yet.

**Comment by zandaqo** [comment]
In theory, this can be left for a directive to do if we are dead set on keeping lit-html minimalist, but I think the proposed solution here is the way to go. Do we have any ETA on this one?

**Comment by LarsDenBakker** [comment]
Would be great to have some resolution on this point, I use quite a lot of boolean properties and it's inconvenient to use lit templates at the moment :)

**Comment by justinfagnani** [comment]
I'd like to align here with the template instantiation proposal, at least for lit-html core. lit-extended can offer more opinionated choices. I think as an initial step we can easily offer a toggle directive, it's just a few lines of code.

**Comment by zandaqo** [comment]
> I'd like to align here with the template instantiation proposal, at least for lit-html core.

As I understand the current proposal, it features a different syntax, I wonder how lit-html is supposed to fit into it.

> I think as an initial step we can easily offer a toggle directive, it's just a few lines of code.

Should we go with the directive then? At least until that proposal shapes up which can take some time, I assume.

**Comment by justinfagnani** [comment]
> As I understand the current proposal, it features a different syntax, I wonder how lit-html is supposed to fit into it.

This isn't necessarily syntax. If the template instantiation spec uses undefined to remove attributes, then I'd want to use that. If the spec uses some special attribute name, likewise. If it uses syntax inside the expression, then a directive would be the way.

**Comment by justinfagnani** [comment]
@jridgewell after discussing with the team, I think we want to go with a syntactical opt-in, like in #197. We're still figuring out the specific semantics of that before merging.

Thanks for the PR!

**Pull request closed without merging**
