### PR TITLE
Fix `envCachesTemplates` for UglifyJS

### LINKED ISSUE #223: UglifyJS overmangles `envCachesTemplates`
Okay, in

```
const envCachesTemplates =
    ((t) => t() === t())(() => ((s) => s) ``)
```

Out: 

```
const envCachesTemplates=(e=>e()==e())(()=>e=>e``);
```

which will evaluate to `false`. 

image

### PR DESCRIPTION
**Pull request by kaste**
Fixes #223 

image

### CODE REVIEW

**Comment by jridgewell** [comment]
Ping @justinfagnani. It's a bug fix, and it actually makes `envCachesTemplates` understandable.

**Comment by stramel** [comment]
@jridgewell did you happen to see #233? I'm just curious if that may be a better fix or not?

**Comment by jridgewell** [comment]
Oo, that's even better.

**Comment by justinfagnani** [comment]
Yeah, I think we can remove this now. It required that lit-html and calling code be compiled with the same compiler anyway, which was kind of a Google-internal-only setup.

Thanks for the fix though @kaste!

**Pull request closed without merging**
