### PR TITLE
Fix binding to attributes after non-bound attributes

### PR DESCRIPTION
**Pull request by justinfagnani**

### CODE REVIEW

**Comment by justinfagnani** [comment]
@sorvell the issue this fixes is breaking some users, could you take a look?

**Comment by justinfagnani** [comment]
The failures on Edge are due to it reordering attributes and the expectation being too strict. Fixing...

**Comment by richardanaya** [comment]
Thank you!

**Comment by justinfagnani** [comment]
Ok, all tests green on all browsers now.

**Pull request merged**
