### PR TITLE
 Allow all valid HTML attribute names.

### LINKED ISSUE #172: Support Angular-style attributes
I'm trying to use angular-style attributes for property/event binding using a custom `render` extension, but I run into an error when trying to call `html` with that syntax.

```js
import {html} from './path/to/lit-html/lit-html.js';

html`<some-element [prop]=${5} (click)=${() => alert('clicked!')}></some-element>`;
```

```
  Cannot read property '1' of null
    <unknown> at   new Template at /components/lit-html/lit-html.js:172:0
    <unknown> at         litTag at /components/lit-html/lit-html.js:43:0
    <unknown> at           html at /components/lit-html/lit-html.js:31:0
```

The `lastAttributeNameRegex` used at [`src/lit-html.ts#L209-210`](https://github.com/PolymerLabs/lit-html/blob/eeafa95c820672ec95231afbc5861d1755d46457/src/lit-html.ts#L209-L210) doesn't match because of the `[]` and `()` in the attribute names.

I've seen comments in #168 that this regex might disappear in the future ([link](https://github.com/PolymerLabs/lit-html/pull/168#discussion_r148941842)). Is this future coming soon or would you accept a PR that adds `[]()` to `lastAttributeNameRegex`?

### PR DESCRIPTION
**Pull request by justinfagnani**
Fixes #172

### CODE REVIEW

**Comment by justinfagnani** [comment]
`npm run lint` which is run from `npm test`

**Comment by justinfagnani** [comment]
which... I forgot to run. CI is calling wct directly, oops.

**Comment by jridgewell** [comment]
It doesn't seem to catch any of the whitespace changes you made?

**Comment by justinfagnani** [comment]
That's just the formatter with `npm run format`. It uses clang-format: https://github.com/PolymerLabs/lit-html/blob/master/package.json#L26

**Pull request merged**
